language: generic
matrix:
  include:
  - os: linux
    env:
    - JOB="linux"
    dist: bionic
    script:
    - export SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2020-02-21-a
    - git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
    - export SWIFTENV_ROOT="$HOME/.swiftenv"
    - export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
    - swiftenv install $SWIFT_VERSION
    - swiftenv rehash
    - utils/test
  - os: osx
    osx_image: xcode11.3
    env:
    - JOB="macos"
    script:
    - brew install imagemagick
    - export SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2020-02-21-a
    - git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
    - export SWIFTENV_ROOT="$HOME/.swiftenv"
    - export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
    - swiftenv install $SWIFT_VERSION
    - swiftenv rehash
    - utils/test
